[package]
name = "note_bit"
version = "0.1.0"
authors = ["nixiesquid <audu817@gmail.com>"]
edition = "2018"

[dependencies]
gio = "0.2.0"
gdk = "0.6.0"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_16"]
